// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7p0fN5P7opUwmnCapL--v13Z1GrBjAGk',
    appId: '1:137939160310:web:ba1a8ce018d8cff47eb0d7',
    messagingSenderId: '137939160310',
    projectId: 'vvxplore-b0d5f',
    authDomain: 'vvxplore-b0d5f.firebaseapp.com',
    databaseURL: 'https://vvxplore-b0d5f-default-rtdb.firebaseio.com',
    storageBucket: 'vvxplore-b0d5f.firebasestorage.app',
    measurementId: 'G-WE1696QXNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvlXje5O2tiTxe3p_vDO3iT_AXolS3CEY',
    appId: '1:137939160310:android:f71b0e1cd2f768fe7eb0d7',
    messagingSenderId: '137939160310',
    projectId: 'vvxplore-b0d5f',
    databaseURL: 'https://vvxplore-b0d5f-default-rtdb.firebaseio.com',
    storageBucket: 'vvxplore-b0d5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXwrPbYJwGezYXG6EGj9lERxLUupgiwqY',
    appId: '1:137939160310:ios:c584a8f8365477457eb0d7',
    messagingSenderId: '137939160310',
    projectId: 'vvxplore-b0d5f',
    databaseURL: 'https://vvxplore-b0d5f-default-rtdb.firebaseio.com',
    storageBucket: 'vvxplore-b0d5f.firebasestorage.app',
    iosBundleId: 'com.example.vvxplore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXwrPbYJwGezYXG6EGj9lERxLUupgiwqY',
    appId: '1:137939160310:ios:c584a8f8365477457eb0d7',
    messagingSenderId: '137939160310',
    projectId: 'vvxplore-b0d5f',
    databaseURL: 'https://vvxplore-b0d5f-default-rtdb.firebaseio.com',
    storageBucket: 'vvxplore-b0d5f.firebasestorage.app',
    iosBundleId: 'com.example.vvxplore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7p0fN5P7opUwmnCapL--v13Z1GrBjAGk',
    appId: '1:137939160310:web:160e0c04c1211de87eb0d7',
    messagingSenderId: '137939160310',
    projectId: 'vvxplore-b0d5f',
    authDomain: 'vvxplore-b0d5f.firebaseapp.com',
    databaseURL: 'https://vvxplore-b0d5f-default-rtdb.firebaseio.com',
    storageBucket: 'vvxplore-b0d5f.firebasestorage.app',
    measurementId: 'G-L20FBBEPH1',
  );

}